### ISSUE TITLE
Error getting Request from Service Manager

### ISSUE THREAD

**Issue by diego-sorribas** [laminas-api-tools/api-tools-content-negotiation#25]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.6.0

#### Summary

Before 1.6 upgrade If I write $container->get('Request') it return me a Laminas\ApiTools\ContentNegotiation\Request, now it return a Laminas\Http\PhpEnvironment\Request, it's that okay?

#### Current behavior

Service Manager return Laminas\Http\PhpEnvironment\Request instead of Laminas\ApiTools\ContentNegotiation\Request

#### How to reproduce
Install a api tools skeleton project and 1.6 version of this packages, in a class implementing FactoryInterface get a Request instance from the container.

#### Expected behavior

I think it has to return a Laminas\ApiTools\ContentNegotiation\Request

**Comment by diego-sorribas** [comment]
I found that if in my code I have this condition:

use Laminas\ApiTools\ContentNegotiation\Request;
if ($request instanceof Request) {}

My code is falling and do not enter in that condition, its that okay?I mean seems a BC change

**Comment by Xerkus** [comment]
I see the change was done in #24

**Comment by diego-sorribas** [comment]
Mmm maybe my error is that I was expecting that MvcEvent getRequest method return a Laminas\ApiTools\ContentNegotiation\Request
